import java.io.*;
import java.util.*;

/**
 * This program is a game loosely based on "Spelling Bee" from the New York
 * times. The user will be presented with 7 unique characters, and they must
 * use the characters to make as many 4+ letter words as they can.
 * 
 * @author Brayden Granger
 */
public class SpellingBee {

    /**
     * Picks a random word from words.txt.
     * 
     * @return The randomly generated word from words.txt
     * @throws FileNotFoundException
     * @throws IOException
     */
    public static String generateWord() throws FileNotFoundException, IOException {
        String word = "";
        int lineCounter = 0;

        FileInputStream fis = new FileInputStream("words.txt");
        Scanner file_sc = new Scanner(fis);

        // Generates a random number up to 8531 and assigns it to wordLine
        Random rnd = new Random();
        int wordLine = rnd.nextInt(8531); // The number of lines in words.txt

        // Cycles through lines in words.txt
        while (file_sc.hasNextLine()) {
            file_sc.nextLine();
            lineCounter++;

            // Checks if wordLine has been reached
            if (lineCounter == wordLine) {
                // Assigns the text at wordLine to word and stops checking
                word = file_sc.nextLine();
                break;
            }
        }

        fis.close();
        file_sc.close();

        return word; // Returns the randomly generated word from words.txt
    }

    /**
     * Checks if the provided word has exactly 7 unique characters.
     * 
     * @param word the word generated by the method generateWord()
     * @return Whether the word is valid
     */
    public static Boolean checkValidity(String word) {
        // First checks if the word is 7 characters long
        if (word.length() == 7) {
            // Then checks each character against each character
            for (int i = 0; i < word.length(); i++) {
                for (int j = i + 1; j < word.length(); j++) {
                    // Then checks if all characters aren't unique
                    if (word.charAt(i) == word.charAt(j)) {
                        return false; // Returns false if the characters aren't all unique
                    }
                }
            }
            return true; // Returns true if the word has exactly 7 unique characters
        } else {
            return false; // Returns false if the word is not 7 characters long
        }
    }

    /**
     * Scrambles the provided word. This should be called only after the validity of
     * the word has been checked.
     * 
     * @param word the word generated by the method generateWord()
     * @return The scrambled word
     */
    public static String scrambleWord(String word) {
        String letter0 = "", letter1 = "", letter2 = "", letter3 = "", letter4 = "", letter5 = "", letter6 = "";
        int doneLetters = 0;

        Random rnd = new Random();

        // Repeats until all 7 letters have been assigned to a new location
        while (doneLetters < 7) {
            // Generates a new number after each case
            int randNum = rnd.nextInt(7);

            // Using the provided word, if a letter located at the randomly generated number
            // has not been assigned to a new location yet, it assigns the letter to the
            // integer doneLetters, which represents the number of letters that have been
            // successfully scrambled so far. It then increases doneLetters by 1. If a
            // letter located at the randomly generated number has already been assigned to
            // a new location, nothing happens.
            switch (randNum) {
                case 0:
                    if (letter0 == "") {
                        letter0 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 1:
                    if (letter1 == "") {
                        letter1 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 2:
                    if (letter2 == "") {
                        letter2 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 3:
                    if (letter3 == "") {
                        letter3 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 4:
                    if (letter4 == "") {
                        letter4 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 5:
                    if (letter5 == "") {
                        letter5 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                case 6:
                    if (letter6 == "") {
                        letter6 = String.valueOf(word.charAt(doneLetters));
                        doneLetters++;
                    } else {
                        break;
                    }
                    break;
                default:
                    break;
            }
        }

        // Combines the individual letters into a new, scrambled word
        word = letter0 + letter1 + letter2 + letter3 + letter4 + letter5 + letter6;

        return word;
    }

    /**
     * Checks if the user input contains the same letters as the provided word
     * regardless of order and number of appearances of each letter.
     * 
     * @param userInput the word the user enters to the terminal
     * @param word      the scrambled word from scrambleWord()
     * @return Whether the user input contains the same letters as the provided word
     * @throws FileNotFoundException
     * @throws IOException
     */
    public static Boolean checkInput1(String userInput, String word) throws FileNotFoundException, IOException {
        int numMatches = 0;

        for (int i = 0; i < word.length(); i++) {
            char wordLetter = word.charAt(i);
            for (int j = 0; j < userInput.length(); j++) {
                if (userInput.charAt(j) == wordLetter) {
                    numMatches++;
                }
            }
            if (numMatches == userInput.length()) {
                return true; // Returns true if user input only contains letters in provided word
            }
        }
        return false; // Returns false if user input contains letters not in provided word
    }

    /**
     * Checks if the user input exists in words.txt.
     * 
     * @param userInput the word the user enters to the terminal
     * @return Whether the user input exists in words.txt.
     * @throws FileNotFoundException
     * @throws IOException
     */
    public static Boolean checkInput2(String userInput) throws FileNotFoundException, IOException {
        FileInputStream fis = new FileInputStream("words.txt");
        Scanner file_sc = new Scanner(fis);
        String tempWord = "";

        // Cycles through lines in words.txt
        while (file_sc.hasNextLine()) {
            tempWord = file_sc.nextLine();

            // Checks if userInput exists in words.txt
            if (userInput.strip().equalsIgnoreCase(tempWord.strip())) {
                fis.close();
                file_sc.close();

                return true; // Returns true if userInput exists in words.txt
            }
        }
        fis.close();
        file_sc.close();

        return false; // Returns false if userInput does not exist in words.txt
    }

    /**
     * Calculates the user's score.
     * 
     * @param userInput the word the user enters to the terminal
     * @param isValid   whether userInput is valid
     * @return The user's score
     */
    public static int addScore(String userInput) {
        int userScore = 0;

        switch (userInput.length()) {
            case 0, 1, 2, 3:
                userScore += 0; // If userInput is shorter than 4 letters, do nothing
                break;
            case 4:
                userScore++; // If userInput is exactly 4 letters, add 1 to score
                break;
            default:
                userScore += userInput.length(); // If userInput is more than 4 letters, add 1 to score for each letter
                break;
        }

        return userScore;
    }

    /**
     * This program is a game loosely based on "Spelling Bee" from the New York
     * times. The user will be presented with 7 unique characters, and they must
     * use the characters to make as many 4+ letter words as they can.
     * 
     * @param args
     * @throws FileNotFoundException
     * @throws IOException
     * @throws NoSuchElementException
     */
    public static void main(String[] args) throws FileNotFoundException, IOException, NoSuchElementException {
        Scanner sc = new Scanner(System.in);
        String word = "", userInput = "", validWords = "";
        int currentScore = 0;

        // Keeps reading from words.txt until it finds a word with 7 unique characters.
        while (checkValidity(word) == false) {
            word = generateWord();
        }

        // Scrambles the word
        word = scrambleWord(word);

        System.out.println("Enter a word containing any combination of the 7 letters displayed below.");
        System.out.println("\tIf the word is invalid or has 3 or less characters, you get no points.");
        System.out.println("\tIf the word is valid and has 4 characters, you get 1 point.");
        System.out.println("\tIf the word is valid and has 5 or more characters, you get 1 point for each letter.");
        System.out.println("Type \"mix\" to display the 7 letters in a new order.");
        System.out.println("Type \"ls\" to display all valid words you have entered so far.");
        System.out.println("Type \"bye\" to exit the program.");

        // Prints the scrambled word with a tab between each character
        System.out.println(word.replace("", "\t"));

        // Takes input from user
        System.out.print("Next word: ");
        userInput = sc.nextLine();

        while (!userInput.strip().equalsIgnoreCase("bye")) {
            // Checks if user inputs "mix"
            if (userInput.strip().equalsIgnoreCase("mix")) {
                // Scrambles the word
                word = scrambleWord(word);

                // Prints the new scrambled word with a tab between each character
                System.out.println(word.replace("", "\t"));
            }

            // Checks if user inputs "ls"
            if (userInput.strip().equalsIgnoreCase("ls")) {
                // Prints all valid words the user has entered so far
                System.out.print(validWords);
            }

            // Checks if the user's word is valid. A word is valid if:
            // a. It only contains letters from word
            // b. It is contained in words.txt
            // c. It hasn't been typed previously
            if (checkInput1(userInput, word) && checkInput2(userInput) && !validWords.contains(userInput)) {
                // If valid, calculates score and adds to validWords
                currentScore += addScore(userInput);
                System.out.println("Score: " + currentScore);

                // Adds userInput to validWords
                validWords += "\t" + userInput + "\n";
            } else {
                // If not valid, just outputs current score
                System.out.println("Score: " + currentScore);
            }

            System.out.print("Next word: ");
            userInput = sc.nextLine();
        }
        System.out.println("Final score: " + currentScore);

        sc.close();
    }
}